Name:           ros-melodic-webrtc
Version:        59.0.3
Release:        0%{?dist}
Summary:        ROS webrtc package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/webrtc
Source0:        %{name}-%{version}.tar.gz

Requires:       alsa-lib
Requires:       glib2-devel
Requires:       gtk2-devel
Requires:       gtk3-devel
Requires:       pulseaudio-libs-devel
BuildRequires:  alsa-lib
BuildRequires:  cmake
BuildRequires:  git
BuildRequires:  glib2-devel
BuildRequires:  gtk2-devel
BuildRequires:  gtk3-devel
BuildRequires:  pulseaudio-libs-devel
BuildRequires:  wget

%description
WebRTC Native API

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Jan 25 2019 Timo Röhling <timo.roehling@fkie.fraunhofer.de> - 59.0.3-0
- Autogenerated by Bloom

* Thu Jan 24 2019 Timo Röhling <timo.roehling@fkie.fraunhofer.de> - 59.0.2-0
- Autogenerated by Bloom

* Thu Jan 24 2019 Timo Röhling <timo.roehling@fkie.fraunhofer.de> - 59.0.1-0
- Autogenerated by Bloom

* Fri Jan 18 2019 Timo Röhling <timo.roehling@fkie.fraunhofer.de> - 59.0.0-0
- Autogenerated by Bloom

