Name:           ros-melodic-webrtc-ros
Version:        59.0.3
Release:        0%{?dist}
Summary:        ROS webrtc_ros package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/webrtc_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-async-web-server-cpp
Requires:       ros-melodic-cv-bridge
Requires:       ros-melodic-image-transport
Requires:       ros-melodic-nodelet
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-webrtc >= 59.0.0
BuildRequires:  ros-melodic-async-web-server-cpp
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cv-bridge
BuildRequires:  ros-melodic-image-transport
BuildRequires:  ros-melodic-nodelet
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-webrtc >= 59.0.0

%description
A collection of ROS utilities for using WebRTC with ROS

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Jan 25 2019 Timo Röhling <timo.roehling@fkie.fraunhofer.de> - 59.0.3-0
- Autogenerated by Bloom

* Thu Jan 24 2019 Timo Röhling <timo.roehling@fkie.fraunhofer.de> - 59.0.2-0
- Autogenerated by Bloom

* Thu Jan 24 2019 Timo Röhling <timo.roehling@fkie.fraunhofer.de> - 59.0.1-0
- Autogenerated by Bloom

* Fri Jan 18 2019 Timo Röhling <timo.roehling@fkie.fraunhofer.de> - 59.0.0-0
- Autogenerated by Bloom

